# Generated by Django 5.2.4 on 2025-08-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dietary_menucategory_remove_menuitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='seasonal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
